from __future__ import annotations

from pathlib import Path
import sys


APP_NAME = "Bebra VPN"
APP_VERSION = "1.0.3"
STATE_SCHEMA_VERSION = 1

PROXY_HOST = "127.0.0.1"
DEFAULT_SOCKS_PORT = 10808
DEFAULT_HTTP_PORT = 10809
DEFAULT_DISCORD_SOCKS_PORT = 10818
DEFAULT_XRAY_STATS_API_PORT = 19085
XRAY_GITHUB_RELEASES_API = "https://api.github.com/repos/XTLS/Xray-core/releases"

ROUTING_GLOBAL = "global"
ROUTING_RULE = "rule"
ROUTING_DIRECT = "direct"
ROUTING_MODES = (ROUTING_GLOBAL, ROUTING_RULE, ROUTING_DIRECT)


def get_base_dir() -> Path:
    if getattr(sys, "frozen", False):
        return Path(sys.executable).resolve().parent
    return Path(__file__).resolve().parents[1]


BASE_DIR = get_base_dir()
DATA_DIR = BASE_DIR / "data"
ASSETS_DIR = BASE_DIR / "assets"
APP_ICON_PATH = ASSETS_DIR / "BebraVPN.ico"
TEMPLATES_DIR = DATA_DIR / "templates"
CONFIGS_DIR = DATA_DIR / "configs"
SINGBOX_TEMPLATES_DIR = TEMPLATES_DIR / "sing-box"
XRAY_TEMPLATES_DIR = TEMPLATES_DIR / "xray"
SINGBOX_CONFIGS_DIR = CONFIGS_DIR / "sing-box"
XRAY_CONFIGS_DIR = CONFIGS_DIR / "xray"
RUNTIME_DIR = DATA_DIR / "runtime"
LOG_DIR = DATA_DIR / "logs"
STATE_FILE = DATA_DIR / "state.enc"
XRAY_CONFIG_FILE = RUNTIME_DIR / "xray_config.json"
XRAY_DEFAULT_CONFIG_NAME = "default.json"
XRAY_PATH_DEFAULT = BASE_DIR / "core" / "xray.exe"
XRAY_TUN_DEFAULT_INTERFACE_NAME = "xray0"

SINGBOX_CONFIG_FILE = RUNTIME_DIR / "singbox_config.json"
SINGBOX_DEFAULT_CONFIG_NAME = "default.json"
SINGBOX_PATH_DEFAULT = BASE_DIR / "core" / "sing-box.exe"
SINGBOX_CLASH_API_PORT = 19090
SINGBOX_XRAY_RELAY_PORT = 11808

SPEED_TEST_DEFAULT_URL = "https://cachefly.cachefly.net/50mb.test"
SPEED_TEST_PING_URL = "https://www.google.com/generate_204"
SPEED_TEST_TIMEOUT = 10  # v2rayN-style timeout per speed test
SPEED_TEST_MIXED_CONCURRENCY = 5
SPEED_TEST_STARTUP_TIMEOUT = 5.0
SPEED_TEST_PING_TIMEOUT = 3.0
SPEED_TEST_MAX_PING_MS = 3500
SPEED_TEST_DOWNLOAD_IDLE_TIMEOUT = 3.0
SPEED_TEST_SLOW_GRACE_SECONDS = 2.5
SPEED_TEST_MIN_BYTES_AFTER_GRACE = 128 * 1024
SPEED_TEST_MIN_MBPS_AFTER_GRACE = 0.2

SS_PROTECT_PORT_START = 19200
SS_PROTECT_PORT_END = 19300
